# pytest.ini

[pytest]
minversion = 6.0
addopts = -ra -q --tb=short
testpaths =
    tests
markers =
    smoke: маркирует смоук-тесты
    regression: регрессионные тесты
    slow: медленные тесты
    flacky: нестабильные тесты